# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Shanika Wijerathna
email: shanikacj@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am Shanika Wijerathna, a Java Developer based in Auckland, New Zealand. In shanika.github.io you will find my various blogs about the new technologies I explore.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://shanika.github.io" # the base hostname & protocol for your site
github_username:  shanika
linkedin_username: shanikaw

# Build settings
markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)


exclude: [shanika.github.io.iml, .gitignore]